name: FlailsTestingTools
main: me.flail.ftt.FTT
version: 1.0
api-version: 1.13
softdepend: 
- MonsterApocalypse

# Nasy stuff
author: FlailoftheLord

commands:
  ftt:
    description: main command
    usage: /ftt help:gmc:gms:gma:gmsp:op:deop:heal:fly <-player>
    
  gmc:
    description: creative mode
    usage: /gmc <-player>
  gms: 
    description: survival mode
    usage: /gms <-player>
  gma:
    description: adventure mode
    usage: /gma <-player>
  gmsp: 
    description: spectator mode
    usage: /gmsp <-player>
  fly:
    description: fly mode
    usage: /fly <-player>
  op:
    description: set op
    usage: /op <-player>
  deop:
    description: unset op
    usage: /deop <-player>
  heal:
    description: heal me pls
    usage: /heal
  plugin:
    description: manage a plugin
    usage: /plugin <-name> reload:disable:enable
  killitems:
    description: kill all dropped items
    usage: /killitems [radius]
  killmobs:
    description: kill nearby mobs
    aliases: [butcher]
    usage: /killmobs [radius]
  
  